# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class MainUI(object):
    def initUI(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(382, 507)
        MainWindow.setMinimumSize(QtCore.QSize(382, 507))
        MainWindow.setMaximumSize(QtCore.QSize(382, 507))
        self.icon = QtGui.QIcon()
        self.icon.addPixmap(QtGui.QPixmap("/usr/share/endeavouros/EndeavourOS-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(self.icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 351, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 341, 18))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 341, 18))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 341, 18))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 90, 341, 18))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 110, 341, 18))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 130, 341, 18))
        self.label_7.setObjectName("label_7")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(20, 160, 111, 24))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 200, 111, 24))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 240, 111, 24))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 280, 121, 24))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 320, 85, 24))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(20, 360, 101, 24))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_7.setGeometry(QtCore.QRect(190, 160, 161, 24))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8.setGeometry(QtCore.QRect(190, 200, 171, 24))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_9.setGeometry(QtCore.QRect(190, 240, 161, 24))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_10.setGeometry(QtCore.QRect(190, 280, 171, 24))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_11.setGeometry(QtCore.QRect(190, 320, 161, 24))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_12.setGeometry(QtCore.QRect(190, 360, 161, 24))
        self.checkBox_12.setObjectName("checkBox_12")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 430, 381, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(100, 400, 161, 24))
        self.radioButton.setObjectName("radioButton")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 450, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 450, 91, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "enlog"))
        self.label.setText(_translate("MainWindow", "Selecting any of the boxes below will add that particular"))
        self.label_2.setText(_translate("MainWindow", "log to a common log file (~/enlog). Once you have "))
        self.label_3.setText(_translate("MainWindow", "checked the desired boxes, select whether you\'d wanna"))
        self.label_4.setText(_translate("MainWindow", "remove any personal data or not. The last step is to"))
        self.label_5.setText(_translate("MainWindow", "either generate a link to share publicly (know that this"))
        self.label_6.setText(_translate("MainWindow", "option removes any personal automatically) or save"))
        self.label_7.setText(_translate("MainWindow", "the file locally. "))
        self.checkBox.setText(_translate("MainWindow", "journalctl -b -0"))
        self.checkBox_2.setText(_translate("MainWindow", "journalctl -b -1"))
        self.checkBox_3.setText(_translate("MainWindow", "journalctl -b -2"))
        self.checkBox_4.setText(_translate("MainWindow", ".xsession-errors"))
        self.checkBox_5.setText(_translate("MainWindow", "Xorg.0.log"))
        self.checkBox_6.setText(_translate("MainWindow", "loghtdm.log"))
        self.checkBox_7.setText(_translate("MainWindow", "x-0.log"))
        self.checkBox_8.setText(_translate("MainWindow", "EndeavourOS install log"))
        self.checkBox_9.setText(_translate("MainWindow", "lspci -vnn"))
        self.checkBox_10.setText(_translate("MainWindow", "systemd-nalyze blame"))
        self.checkBox_11.setText(_translate("MainWindow", "lsusb"))
        self.checkBox_12.setText(_translate("MainWindow", "hwinfo --short"))
        self.radioButton.setText(_translate("MainWindow", "Remove personal info"))
        self.pushButton.setText(_translate("MainWindow", "Generate link"))
        self.pushButton_2.setText(_translate("MainWindow", "Save locally"))